# Site settings
title: "XiongJJ's blog"
email: krimson8@gmail.com 
description: "A blog for technical/programming problems."
baseurl: ""
url: ""
title_description: "A blog recording the technical/programming problems I have met in daily life, probably comes with a solution. Site builded with jekyll + github pages, with 'Carte Noire' theme"
title_image: "https://i.imgur.com/Jf7KSsn.jpg"
google_analytics: ""
disqus_account: 
github_repository: 
post_limit: 5

# Social usernames/URLs
github_username:  krimson8
linkedin_link: 
facebook_link:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
