# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: "XiongJJ's blog"
subtitle: "A blog for technical/programming problems."
email: krimson8@gmail.com
name: XiongJJ
description: "A blog for technical/programming problems, probably comes with solutions."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://krimson8.github.io" # the base hostname & protocol for your site
cover: "/assets/header_image.jpg"
logo: "/assets/logo.jpg"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Disqus comments
disqus_shortname: xiongjj-blog

# Google analytics
ga_tracking_id: "UA-136296852-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."
  - cat: linux
    desc: "Posts showing linux utilities or system calls usage."
  - cat: update
    desc: "Non-technical stuff blog, possibly helpful in various life situations."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Facebook
    icon: facebook
    username: Xiong Jia
    url: https://www.facebook.com/xiong.jia.5
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: krimson8 
    url: https://github.com/krimson8 
    desc: Check out my other projects
    share: false

# - name: LinkedIn
#    icon: linkedin
#    username: Ben Centra
#    url: https://www.linkedin.com/pub/ben-centra/47/769/60a
#    desc: Connect with me on LinkedIn
#    share: true

